/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIS;

/**
 *
 * @author BLiyanage
 */
public class FinishAll extends javax.swing.JFrame {

    /**
     * Creates new form FinishAll
     */
    public FinishAll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finishAll = new javax.swing.JPanel();
        displayStatus1 = new javax.swing.JLabel();
        displayStatus = new javax.swing.JLabel();
        statusLabel1 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        statusLabel2 = new javax.swing.JLabel();
        displayStatus2 = new javax.swing.JLabel();
        statusLabel3 = new javax.swing.JLabel();
        displayStatus3 = new javax.swing.JLabel();
        statusLabel4 = new javax.swing.JLabel();
        displayStatus4 = new javax.swing.JLabel();
        statusLabel5 = new javax.swing.JLabel();
        displayStatus5 = new javax.swing.JLabel();
        statusLabel6 = new javax.swing.JLabel();
        displayStatus6 = new javax.swing.JLabel();
        statusLabel7 = new javax.swing.JLabel();
        displayStatus7 = new javax.swing.JLabel();
        statusLabel8 = new javax.swing.JLabel();
        displayStatus8 = new javax.swing.JLabel();
        statusLabel9 = new javax.swing.JLabel();
        displayStatus9 = new javax.swing.JLabel();
        finishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        finishAll.setBackground(new java.awt.Color(255, 255, 255));

        statusLabel1.setText("Issue Time:");

        statusLabel.setText("Issue Date:");

        statusLabel2.setText("DueTime:");

        statusLabel3.setText("Due Date:");

        statusLabel4.setText("Duration:");

        statusLabel5.setText("Overdue Hrs:");

        statusLabel6.setText("Rental Price:");

        statusLabel7.setText("First Instalment:");

        statusLabel8.setText("Overdue Price:");

        statusLabel9.setText("Total Price:");

        finishButton.setText("Finish");

        javax.swing.GroupLayout finishAllLayout = new javax.swing.GroupLayout(finishAll);
        finishAll.setLayout(finishAllLayout);
        finishAllLayout.setHorizontalGroup(
            finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finishAllLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel2)
                    .addComponent(statusLabel5)
                    .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(statusLabel6)
                        .addGroup(finishAllLayout.createSequentialGroup()
                            .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(finishAllLayout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(statusLabel8))
                                .addComponent(statusLabel9))
                            .addGap(74, 74, 74)
                            .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(finishAllLayout.createSequentialGroup()
                                    .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(displayStatus9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displayStatus8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(finishAllLayout.createSequentialGroup()
                            .addComponent(statusLabel7)
                            .addGap(68, 68, 68)
                            .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(displayStatus7, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(displayStatus6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displayStatus5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displayStatus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(finishAllLayout.createSequentialGroup()
                            .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(statusLabel4)
                                .addComponent(statusLabel3)
                                .addComponent(statusLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                            .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(displayStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(displayStatus4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(displayStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(displayStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(statusLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        finishAllLayout.setVerticalGroup(
            finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finishAllLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(finishAllLayout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(statusLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(finishAllLayout.createSequentialGroup()
                        .addComponent(displayStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayStatus4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(displayStatus3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel2)
                    .addComponent(displayStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel5)
                    .addComponent(displayStatus5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel6)
                    .addGroup(finishAllLayout.createSequentialGroup()
                        .addComponent(displayStatus6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayStatus7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayStatus8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(finishAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayStatus9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finishAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finishAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinishAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinishAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinishAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinishAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinishAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayStatus;
    private javax.swing.JLabel displayStatus1;
    private javax.swing.JLabel displayStatus2;
    private javax.swing.JLabel displayStatus3;
    private javax.swing.JLabel displayStatus4;
    private javax.swing.JLabel displayStatus5;
    private javax.swing.JLabel displayStatus6;
    private javax.swing.JLabel displayStatus7;
    private javax.swing.JLabel displayStatus8;
    private javax.swing.JLabel displayStatus9;
    private javax.swing.JPanel finishAll;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusLabel1;
    private javax.swing.JLabel statusLabel2;
    private javax.swing.JLabel statusLabel3;
    private javax.swing.JLabel statusLabel4;
    private javax.swing.JLabel statusLabel5;
    private javax.swing.JLabel statusLabel6;
    private javax.swing.JLabel statusLabel7;
    private javax.swing.JLabel statusLabel8;
    private javax.swing.JLabel statusLabel9;
    // End of variables declaration//GEN-END:variables
}
