/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIS;

import Database.DB;
import SystemHandling.CustomerHandling;
import SystemHandling.DoRent;
import SystemHandling.VehicleHandling;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author BLiyanage
 */
public class RentAVehicle extends javax.swing.JFrame {
      
    public RentAVehicle() {
        initComponents();
    }
    
    static Vector listOfAttr;
    int cusNo = CustomerHandling.cusNo;
    String issueDate = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    GregorianCalendar gcalendar = new GregorianCalendar();
    String issueTime = gcalendar.get(Calendar.HOUR) +":"+ gcalendar.get(Calendar.MINUTE);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RentAVehiclePanel = new javax.swing.JPanel();
        CategoryTitle = new javax.swing.JLabel();
        issueDateField = new javax.swing.JTextField();
        rentalPriceLabel = new javax.swing.JLabel();
        customerNoLabel = new javax.swing.JLabel();
        issueTimeField = new javax.swing.JTextField();
        customerNoField = new javax.swing.JTextField();
        issueDateLabel = new javax.swing.JLabel();
        vehicleNameLabel = new javax.swing.JLabel();
        issueTimeLabel = new javax.swing.JLabel();
        EmpNoLabel = new javax.swing.JLabel();
        vehicleNoField = new javax.swing.JTextField();
        vehicleTypeField = new javax.swing.JTextField();
        vehicleNameField = new javax.swing.JTextField();
        vehicleTypeLabel = new javax.swing.JLabel();
        rentalPriceField = new javax.swing.JTextField();
        vehicleLicenseLabel = new javax.swing.JLabel();
        dueDateField = new javax.swing.JTextField();
        dueDateLabel = new javax.swing.JLabel();
        dueTimeLabel = new javax.swing.JLabel();
        dueTimeField = new javax.swing.JTextField();
        durationLabel = new javax.swing.JLabel();
        durationField = new javax.swing.JTextField();
        clearRentalButton = new javax.swing.JButton();
        addRentalButton = new javax.swing.JButton();
        closeAllButton = new javax.swing.JButton();
        EmpNoCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        installmentField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a rent");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        RentAVehiclePanel.setBackground(new java.awt.Color(255, 255, 255));

        CategoryTitle.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        CategoryTitle.setText("rent a vehicle:");

        rentalPriceLabel.setText("Rental Price:");

        customerNoLabel.setText("Customer No:");

        issueDateLabel.setText("Issue Date:");

        vehicleNameLabel.setText("Vehicle Name:");

        issueTimeLabel.setText("Issue Time:");

        EmpNoLabel.setText("Employee No:");

        vehicleTypeLabel.setText("Vehicle Type:");

        vehicleLicenseLabel.setText("Vehicle License No:");

        dueDateField.setText("yyyy-mm-dd");

        dueDateLabel.setText("Due Date:");

        dueTimeLabel.setText("Due Time:");

        dueTimeField.setText("hh:mm");

        durationLabel.setText("Duration:");

        clearRentalButton.setText("Clear");
        clearRentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearRentalButtonActionPerformed(evt);
            }
        });

        addRentalButton.setText("Rent");
        addRentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRentalButtonActionPerformed(evt);
            }
        });

        closeAllButton.setText("CloseAll");
        closeAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAllButtonActionPerformed(evt);
            }
        });

        EmpNoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EmpId" }));

        jLabel1.setText("First Installment:");

        javax.swing.GroupLayout RentAVehiclePanelLayout = new javax.swing.GroupLayout(RentAVehiclePanel);
        RentAVehiclePanel.setLayout(RentAVehiclePanelLayout);
        RentAVehiclePanelLayout.setHorizontalGroup(
            RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RentAVehiclePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RentAVehiclePanelLayout.createSequentialGroup()
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EmpNoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(customerNoLabel))
                            .addComponent(durationLabel)
                            .addComponent(issueTimeLabel)
                            .addComponent(dueDateLabel)
                            .addComponent(issueDateLabel)
                            .addComponent(vehicleNameLabel)
                            .addComponent(rentalPriceLabel)
                            .addComponent(dueTimeLabel)
                            .addComponent(vehicleTypeLabel)
                            .addComponent(jLabel1)
                            .addComponent(vehicleLicenseLabel))
                        .addGap(31, 31, 31)
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dueTimeField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(dueDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(vehicleNoField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(customerNoField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(vehicleTypeField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(vehicleNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(rentalPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(issueDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(issueTimeField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(durationField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(EmpNoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(RentAVehiclePanelLayout.createSequentialGroup()
                                .addComponent(addRentalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearRentalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(installmentField))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        RentAVehiclePanelLayout.setVerticalGroup(
            RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RentAVehiclePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CategoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RentAVehiclePanelLayout.createSequentialGroup()
                        .addComponent(customerNoLabel)
                        .addGap(20, 20, 20)
                        .addComponent(EmpNoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RentAVehiclePanelLayout.createSequentialGroup()
                        .addComponent(customerNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmpNoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleLicenseLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleTypeLabel))
                        .addGap(8, 8, 8)
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rentalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rentalPriceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issueDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issueDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issueTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issueTimeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dueDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dueDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dueTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dueTimeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durationLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(installmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(RentAVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRentalButton)
                    .addComponent(clearRentalButton)
                    .addComponent(closeAllButton))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RentAVehiclePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RentAVehiclePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void closeAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAllButtonActionPerformed
         System.exit(1);
    }//GEN-LAST:event_closeAllButtonActionPerformed
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getEmpNo();
        addToFields();
    }//GEN-LAST:event_formWindowOpened

    private void clearRentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearRentalButtonActionPerformed
        customerNoField.setText("");
        vehicleNoField.setText("");
        vehicleTypeField.setText("");
        vehicleNameField.setText("");
        rentalPriceField.setText("");
        issueDateField.setText("");
        issueTimeField.setText("");
        EmpNoCombo.removeAllItems();
        dueDateField.setText("");
        dueTimeField.setText("");
        durationField.setText("");
        installmentField.setText("");
    }//GEN-LAST:event_clearRentalButtonActionPerformed

    private void addRentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRentalButtonActionPerformed
        //int cusId = Integer.parseInt(customerNoField.getText());
        String vehiNo = vehicleNoField.getText();
        String vehiType = vehicleTypeField.getText();
        String vehiName = vehicleNameField.getText();
        double rentPrice = Double.parseDouble(rentalPriceField.getText());
        
        int empId=0;
        try{
            empId = Integer.parseInt(EmpNoCombo.getSelectedItem().toString());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Select Employee Id");
        }
        
        String dueDate = dueDateField.getText();
        String dueTime = dueTimeField.getText();
        int duration = Integer.parseInt(durationField.getText());
        double install = Double.parseDouble(installmentField.getText());
    
        //for rental_detail_no to search for vehicle rental price
        int rentalNo=0;
        try {
            ResultSet payment_rs = DB.getConnect().executeQuery("SELECT rent_detail_no FROM payment_details WHERE vehicle_type = '"+vehiType+"'");
            
            if(payment_rs.last()){
                rentalNo = payment_rs.getInt("rent_detail_no");
            }
            
            DB.getConnect().executeUpdate("INSERT INTO rental(issue_date, issue_time, duration, due_date, due_time, "
                    + "VehicleLicenseNo, empId, cusId, rental_status, rent_detail_no, rental_price, first_installment) VALUES('"+issueDate+"',"
                    + "'"+issueTime+"', '"+duration+"', '"+dueDate+"', '"+dueTime+"', '"+vehiNo+"', '"+empId+"', '"+cusNo+"',"
                    + "'"+"pending"+"', '"+2+"', '"+rentPrice+"', '"+install+"')");
            JOptionPane.showMessageDialog(null, "Rental added");
            DB.getConnect().executeUpdate("UPDATE vehicle SET onhand='"+0+"' WHERE VehicleLicenseNo = '"+vehiNo+"'");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "cannot add rental now..");
        }
    }//GEN-LAST:event_addRentalButtonActionPerformed

    public void getEmpNo(){
        try {
            ResultSet rs = DB.getConnect().executeQuery("SELECT empId FROM employee");
            while(rs.next()){
                EmpNoCombo.addItem(rs.getInt("empId"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No Employee found");
        }
    }
    
    public void addToFields(){
        customerNoField.setText(cusNo+"");
        vehicleNoField.setText(listOfAttr.get(0)+"");
        vehicleTypeField.setText(listOfAttr.get(1)+"");
        vehicleNameField.setText(listOfAttr.get(2)+"");
        rentalPriceField.setText(listOfAttr.get(7)+"");
        issueDateField.setText(issueDate);
        issueTimeField.setText(issueTime);
    }
    
    public void getAll(Vector v){
        listOfAttr = v;
    }
    
    public void setCustomerNo(int no){
        cusNo = no;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentAVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentAVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentAVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentAVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentAVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryTitle;
    private javax.swing.JComboBox EmpNoCombo;
    private javax.swing.JLabel EmpNoLabel;
    private javax.swing.JPanel RentAVehiclePanel;
    private javax.swing.JButton addRentalButton;
    private javax.swing.JButton clearRentalButton;
    private javax.swing.JButton closeAllButton;
    private javax.swing.JTextField customerNoField;
    private javax.swing.JLabel customerNoLabel;
    private javax.swing.JTextField dueDateField;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JTextField dueTimeField;
    private javax.swing.JLabel dueTimeLabel;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField installmentField;
    private javax.swing.JTextField issueDateField;
    private javax.swing.JLabel issueDateLabel;
    private javax.swing.JTextField issueTimeField;
    private javax.swing.JLabel issueTimeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField rentalPriceField;
    private javax.swing.JLabel rentalPriceLabel;
    private javax.swing.JLabel vehicleLicenseLabel;
    public javax.swing.JTextField vehicleNameField;
    private javax.swing.JLabel vehicleNameLabel;
    private javax.swing.JTextField vehicleNoField;
    private javax.swing.JTextField vehicleTypeField;
    private javax.swing.JLabel vehicleTypeLabel;
    // End of variables declaration//GEN-END:variables
}
